name: CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            docker exec $(docker compose ps -q mysql) mysqladmin ping -uroot -prootpassword --silent && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run migrations
        run: docker compose exec app php artisan migrate --force

      - name: Run tests
        run: docker compose exec app php artisan test

      - name: Run PHPStan static analysis
        run: docker compose exec app vendor/bin/phpstan analyse

      - name: Run Laravel Pint code style check
        run: docker compose exec app vendor/bin/pint --test

      - name: Generate Swagger docs and check changes
        run: |
          docker compose exec app php artisan l5-swagger:generate
          git diff --exit-code public/docs/swagger.json
