name: CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start Docker containers
        run: docker compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            docker exec $(docker compose ps -q mysql) mysqladmin ping -uroot -prootpassword --silent && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Install PHP dependencies
        run: docker compose exec app composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node dependencies
        run: docker compose exec app npm ci --no-audit --no-progress

      - name: Run migrations for main DB
        run: docker compose exec app php artisan migrate --force

      - name: Run migrations for test DB
        run: docker compose exec app php artisan migrate --force --env=testing

      - name: Run tests
        run: docker compose exec app php artisan test --testsuite=Feature

      - name: Run PHPStan static analysis
        run: docker compose exec app vendor/bin/phpstan analyse

      - name: Run Laravel Pint code style check
        run: docker compose exec app vendor/bin/pint --test

      - name: Generate Swagger docs and check changes
        run: |
          docker compose exec app php artisan l5-swagger:generate
          git diff --exit-code storage/api-docs/api-docs.json
